# Generated by Django 3.2.15 on 2022-08-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinfo',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
