# Generated by Django 3.2.15 on 2022-08-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220821_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='product',
            field=models.ManyToManyField(related_name='product_business_map', to='app.Product'),
        ),
        migrations.DeleteModel(
            name='BusinessProduct',
        ),
    ]
