# Generated by Django 3.2.15 on 2022-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220821_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ManyToManyField(related_name='product_business_map', to='app.Business'),
        ),
    ]
