# Generated by Django 3.2.15 on 2022-08-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220821_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='business',
        ),
        migrations.AddField(
            model_name='business',
            name='product',
            field=models.ManyToManyField(related_name='business_product_map', to='app.Product'),
        ),
    ]
